name       : nautilus-admin
version    : 1.1.1
release    : 2
source     :
    - https://github.com/brunonova/nautilus-admin/archive/v1.1.1.tar.gz : 60765e6402c4193c5bc419e3900887452ca5c61bac69ab530fc0c7068c022d27
license    : GPL-3.0
component  : desktop.gnome
summary    : Extension for Nautilus to do administrative operations
description: |
    Extension for Nautilus to do administrative operations
builddeps  :
    - pkgconfig(libnautilus-extension)
rundeps    :
    - nautilus-python
setup      : |
    %cmake . -DCMAKE_INSTALL_PREFIX=/usr
build      : |
    %make
install    : |
    %make_install
