name       : nautilus-admin
version    : 1.1.9
release    : 3
source     :
    - https://github.com/brunonova/nautilus-admin/archive/v1.1.9.tar.gz : 12a36d1298fbe4065e0dba8f1a48312950fe116a503a4c44a7547d0fb322bc1a
license    : GPL-3.0
component  : desktop.gnome
summary    : Extension for Nautilus to do administrative operations
description: |
    Extension for Nautilus to do administrative operations
builddeps  :
    - pkgconfig(libnautilus-extension)
rundeps    :
    - nautilus-python
setup      : |
    %cmake . -DCMAKE_INSTALL_PREFIX=/usr
build      : |
    %make
install    : |
    %make_install
